services:
  sidabi_db:
    container_name: sidabi_database
    image: postgres:13.20
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_postgres/pg_data:/var/lib/postgresql/data/
      - ./database_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database_postgres/pg_dump:/var/backups
    networks:
      - sidabi_server

  sidabi_app:
    container_name: sidabi_application
    build:
      context: ./Compose-sidabi/sidabi_app
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $DB_HOST -p 5432 -U $POSTGRES_USER"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "80:80"
    volumes:
      - sensor-files:/var/www/sidabi/biodata/files/sessao_arquivos/
    depends_on:
      sidabi_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - sidabi_server

networks:
  sidabi_server:
    driver: bridge
volumes:
  sensor-files: